import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProps } from "next/app";
import { CartProvider } from "../context/CartContext";
import { LanguageProvider } from "@inlang/paraglide-js-adapter-next";
import { languageTag } from "@/paraglide/runtime";
import * as m from "@/paraglide/messages";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// src/app/layout.tsx (або в іншому файлі, де є хедер)
import Link from "next/link";
import CartIcon from "@/components/CartIcon";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

const Header = () => {
  return (
    <header className="p-4 bg-gray-800 text-white flex justify-between items-center">
      <Link href="/">{m.home()}</Link>
      <Link href="/cart" className="ml-4">
        <CartIcon />
      </Link>
      <LanguageSwitcher />
    </header>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html lang={languageTag()}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </body>
      </html>
    </LanguageProvider>
  );
}
