import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProps } from "next/app";
import { CartProvider } from "../context/CartContext";
import { LanguageProvider } from "@inlang/paraglide-js-adapter-next";
import { languageTag } from "@/paraglide/runtime";
import * as m from "@/paraglide/messages";
import { Header } from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// src/app/layout.tsx (або в іншому файлі, де є хедер)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html lang={languageTag()}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </body>
      </html>
    </LanguageProvider>
  );
}
